name: 'Upload to S3'
description: 'Upload Index file to S3 for Static Web Hosting'
inputs:
  bucket-name:
    description: 'Name of the S3 bucket'
    required: true
  bucket-region:
    description: 'Region in which bucket is created'
    required: true
  dist-folder:
    description: 'Folder containing deployable file'
    required: true
outputs:
  website-url:
    description: 'The URL of the static S3 Website'
runs:
  using: 'node20'             #updated the version from 16 to 20
  main: 'main.js'