name: Deployment OIDC
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Load & Cache Dependencies
        uses: ./.github/actions/cache-deps
        with:
          caching: 'false'
      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Load & Cache Dependencies
        uses: ./.github/actions/cache-deps
      - name: Test code
        id: run-tests
        run: npm run test
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Load & Cache Dependencies
        uses: ./.github/actions/cache-deps
      - name: Build website
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: prod
    permissions:
        id-token: write   # This is required for requesting the JWT
        contents: read    # This is required for actions/checkout
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: ./dist
      - name: Output contents
        run: ls
        ## Added this to install dependencies on the runner instead of pushing node modules folder to git repo
        ## Updated versions in package.json as default ones are not compatible 
      - name: Install S3 action dependencies        
        run: npm install
        working-directory: ./.github/actions/S3
      - name: Get AWS permissions
        uses: aws-actions/configure-aws-credentials@v6
        env:
            role_arn: ${{secrets.role_Arn}}
        with:
            aws-region: us-east-1
            role-to-assume: ${{env.role_arn}}
      - name: Deploy site
        id: deploy
        uses: ./.github/actions/S3/
        with:
          bucket-name: 'roy-gha-s3'
          bucket-region: 'us-east-1'
          dist-folder: './dist'
      - name: Out Website URL
        run: echo "The S3 static Website URL is - ${{steps.deploy.outputs.website-url}}"
